# Generated by Django 5.1.5 on 2025-01-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], max_length=50),
        ),
    ]
