# Generated by Django 5.1.5 on 2025-01-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('hotel owner', 'Hotel Owner'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='HotelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_hotel_name', models.CharField(max_length=300)),
                ('hotel_bio', models.CharField(max_length=300)),
                ('hotel_cover', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('image1', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('image2', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('image3', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('hotel_seats', models.IntegerField()),
                ('no_people_per_hour', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='menu_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.hotelprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('bio', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
