# Generated by Django 5.1.5 on 2025-01-28 23:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hotelpicture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1738105543/pfp_birubd.jpg', max_length=255, verbose_name='image'),
        ),
    ]
