# Generated by Django 5.1.5 on 2025-01-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='location',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
