# Generated by Django 5.1.5 on 2025-01-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hotelprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('bnb', 'Beb & Breakfast-(B&B)'), ('motel', 'Motel'), ('lodge', 'Lodge'), ('themed_dining_xp', 'Themed Dining XP')], default='hotel', max_length=50),
        ),
    ]
