# Generated by Django 5.1.5 on 2025-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_location_userprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('bnb', 'Beb & Breakfast-(B&B)'), ('motel', 'Motel'), ('lodge', 'Lodge'), ('themed_dining_xp', 'Themed Dining XP')], default='hotel', max_length=50),
        ),
    ]
