# Generated by Django 5.1.5 on 2025-01-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_userprofile_location_remove_userprofile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprofile',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('b&b', 'Beb & Breakfast-(B&B)'), ('motel', 'Motel'), ('lodge', 'Lodge'), ('themed_dining_xp', 'Themed Dining XP')], default='hotel', max_length=50),
        ),
    ]
