# Generated by Django 5.1.5 on 2025-02-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelprofile',
            old_name='hotel_seats',
            new_name='hotel_tables',
        ),
        migrations.RemoveField(
            model_name='hotelprofile',
            name='no_people_per_hour',
        ),
    ]
