# Generated by Django 5.1.5 on 2025-02-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_menuitem_type_bookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='number',
            field=models.IntegerField(default='1'),
        ),
    ]
