# Generated by Django 5.1.5 on 2025-02-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_bookingmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
