# Generated by Django 5.1.5 on 2025-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_hotelprofile_email_hotelprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='hotel_table_seats',
            field=models.IntegerField(default=0),
        ),
    ]
