# Generated by Django 5.1.5 on 2025-02-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_hotelprofile_hotel_table_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='state',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('deny', 'deny')], default='Table', max_length=50),
        ),
    ]
