# Generated by Django 5.1.5 on 2025-02-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_bookingmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='state',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('deny', 'deny')], default='pending', max_length=50),
        ),
    ]
