# Generated by Django 5.1.5 on 2025-02-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_bookingmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='state',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('reject', 'reject')], default='pending', max_length=50),
        ),
    ]
