# Generated by Django 5.1.5 on 2025-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_bookingmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='message',
            field=models.CharField(default='Pending...'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='state',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
