# Generated by Django 5.1.5 on 2025-01-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_stk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesaresponse',
            old_name='chechout_request_id',
            new_name='checkout_request_id',
        ),
    ]
