# Generated by Django 5.1.5 on 2025-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_stk', '0002_rename_chechout_request_id_mpesaresponse_checkout_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaresponse',
            name='customer_message',
            field=models.CharField(max_length=255),
        ),
    ]
